config/routes.rb
PandaShared::Application.routes.draw do
  resources :series_sets

  resources :series_log_items

  resources :series

  resources :series_scenarios

  resources :diagnosis_methods

  resources :diagnoses

  resources :scanner_hardwares

  resources :mri_scans

  resources :races

  resources :researchers

  resources :appointments

  resources :visits

  resources :enrollments

  resources :participants

  root :to => "participants#index"

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  has_many :enrollment_visit_memberships
  has_many :enrollments, :through => :enrollment_visit_memberships
  has_many :appointments
  has_many :visit_diagnoses
  has_many :diagnoses, :through => :visit_diagnoses
  
  accepts_nested_attributes_for :visit_diagnoses, :reject_if => :all_blank
  
  scope :without_appointments, where("id NOT IN (SELECT visit_id FROM appointments)")

  acts_as_reportable :except => [:created_at, :updated_at]
  
  # TODO: ActsAsList seems to have some incompatibility with factory_girl
  # acts_as_list :scope => :enrollment, :column => :visit_number
  
  
  def participant
    enrollments.first.participant unless enrollments.empty?
  end
  
  # Pretty list of enumber(s)
  def enumbers
    enrollments.collect{|e| e.enumber}.join(', ') unless enrollments.empty?
  end
  
  # Visit date is just first appointment date
  def visit_date
    unless appointments.blank?
      appointments.sort_by(&:appointment_date).first.appointment_date
    else
      '<no date>'
    end
  end
  
  # Most recent diagnosis
  def current_diagnosis
    unless visit_diagnoses.blank?
      visit_diagnoses.sort_by(&:diagnosis_date).first.characterization
    else
      'No Dx'
    end
  end
  
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # GET /visits
  # GET /visits.xml
  def index
    @search = default_search(Visit)
    @visits = @search.relation.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @visits }
    end
  end

  # GET /visits/1
  # GET /visits/1.xml
  def show
    @visit = Visit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.xml
  def new
    @visit = Visit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @visit }
    end
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
    @visit.visit_diagnoses.build if @visit.visit_diagnoses.blank?
  end

  # POST /visits
  # POST /visits.xml
  def create
    @visit = Visit.new(params[:visit])

    respond_to do |format|
      if @visit.save
        format.html { redirect_to(@visit, :notice => 'Visit was successfully created.') }
        format.xml  { render :xml => @visit, :status => :created, :location => @visit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @visit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.xml
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to(@visit, :notice => 'Visit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @visit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.xml
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to(visits_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%#= form_for(@visit) do |f| %>
<%= simple_form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	  <%= f.input :visit_number %>
		<%= f.input :scan_note %>
	
		<%= f.simple_fields_for :visit_diagnoses do |visit_dx_fields| %>
			<%#= f.inputs :diagnosis, :for => :visit_diagnosis do  %>
			<%= visit_dx_fields.association :diagnosis, :collection => Diagnosis.all, :label_method => :characterization %>
			<%= visit_dx_fields.association :diagnosis_method, :collection => DiagnosisMethod.all, :label_method => :consensus_method %>
			<%= visit_dx_fields.input :diagnosis_date, :as => :date, :include_blank => true %>
			<%= visit_dx_fields.association :diagnoser, :collection => Researcher.all.sort_by(&:initials), :label_method => :initials %>
		<% end %>
		
		<%= f.collection_check_boxes :enrollment_ids, @visit.participant.enrollments, :id, :enumber unless @visit.participant.blank? %>

	<%= f.button :submit %>


	<%# end %>
	

  <!-- <div class="field">
    <%= f.label :visit_number %><br />
    <%= f.text_field :visit_number %>
  </div>
  <div class="field">
    <%= f.label :scan_note %><br />
    <%= f.text_area :scan_note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div> -->
<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %> |
<%= link_to 'Destroy', @visit, :confirm => 'Are you sure?', :method => :delete %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>

<table>
	<tfoot><tr><td colspan="5"><%= paginate @visits %></td></tr></tfoot>
	<tr>
		<th><%= sort_link @search, :id %></th>
		<th><%= sort_link @search, :enrollments_enumber, "Enumbers" %></th>
		<th><%= sort_link @search, :visit_number %></th>
		<th><%= sort_link @search, :appointments_appointment_date, "Appointments" %></th>
		<th>Diagnosis<%#= sort_link @search, :current_diagnosis, "Diagnosis" %></th>
		<th>Scan note</th>
  </tr>

<% @visits.each do |visit| %>
	<tr>
		<td><%= link_to visit.id, visit %></td>
		<td><%= visit.enumbers %></td>
		<td><%= visit.visit_number %></td>
		<td><%= visit.appointments.collect{|a| link_to a.appointment_date, a }.join(', ').html_safe %></td>
		<td><%= visit.current_diagnosis %></td>
		<td><%= visit.scan_note %></td>
	</tr>
<% end %>
</table>

<br />

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Visit number:</b>
  <%= @visit.visit_number %>
</p>

<p>
  <b>Scan note:</b>
  <%= @visit.scan_note %>
</p>
<% unless @visit.enrollments.blank? %>
<%= render :partial => 'enrollments/enrollments_ul', :object => @visit.enrollments %>
<% else %>
<h2>No Enrollments found.</h2>
<% end %>

<% unless @visit.appointments.blank? %>
	<%= render :partial => 'appointments/appointments_ul', :object => @visit.appointments %>
<% else %>
	<h2>No Appointments found.</h2>
<% end %>

<% unless @visit.diagnoses.blank? %>
	<%= render @visit.visit_diagnoses  %>
<% else %>
	<h2>No Diagnosis (Assumed Healthy Control)</h2>
<% end %>

<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>