config/routes.rb
PandaShared::Application.routes.draw do
  resources :series_sets

  resources :series_log_items

  resources :series

  resources :series_scenarios

  resources :diagnosis_methods

  resources :diagnoses

  resources :scanner_hardwares

  resources :mri_scans

  resources :races

  resources :researchers

  resources :appointments

  resources :visits

  resources :enrollments

  resources :participants

  root :to => "participants#index"

end

app/models/scanner_hardware.rb
class ScannerHardware < ActiveRecord::Base
  validates_presence_of :name, :hardware_group
  
  has_many :mri_scans
end

app/controllers/scanner_hardwares_controller.rb
class ScannerHardwaresController < ApplicationController
  # GET /scanner_hardwares
  # GET /scanner_hardwares.xml
  def index
    @scanner_hardwares = ScannerHardware.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scanner_hardwares }
    end
  end

  # GET /scanner_hardwares/1
  # GET /scanner_hardwares/1.xml
  def show
    @scanner_hardware = ScannerHardware.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @scanner_hardware }
    end
  end

  # GET /scanner_hardwares/new
  # GET /scanner_hardwares/new.xml
  def new
    @scanner_hardware = ScannerHardware.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @scanner_hardware }
    end
  end

  # GET /scanner_hardwares/1/edit
  def edit
    @scanner_hardware = ScannerHardware.find(params[:id])
  end

  # POST /scanner_hardwares
  # POST /scanner_hardwares.xml
  def create
    @scanner_hardware = ScannerHardware.new(params[:scanner_hardware])

    respond_to do |format|
      if @scanner_hardware.save
        format.html { redirect_to(@scanner_hardware, :notice => 'Scanner hardware was successfully created.') }
        format.xml  { render :xml => @scanner_hardware, :status => :created, :location => @scanner_hardware }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @scanner_hardware.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scanner_hardwares/1
  # PUT /scanner_hardwares/1.xml
  def update
    @scanner_hardware = ScannerHardware.find(params[:id])

    respond_to do |format|
      if @scanner_hardware.update_attributes(params[:scanner_hardware])
        format.html { redirect_to(@scanner_hardware, :notice => 'Scanner hardware was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @scanner_hardware.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scanner_hardwares/1
  # DELETE /scanner_hardwares/1.xml
  def destroy
    @scanner_hardware = ScannerHardware.find(params[:id])
    @scanner_hardware.destroy

    respond_to do |format|
      format.html { redirect_to(scanner_hardwares_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/scanner_hardwares_helper.rb
module ScannerHardwaresHelper
end

app/views/scanner_hardwares/_form.html.erb
<%= form_for(@scanner_hardware) do |f| %>
  <% if @scanner_hardware.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scanner_hardware.errors.count, "error") %> prohibited this scanner_hardware from being saved:</h2>

      <ul>
      <% @scanner_hardware.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hardware_group %><br />
    <%= f.text_field :hardware_group %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scanner_hardwares/edit.html.erb
<h1>Editing scanner_hardware</h1>

<%= render 'form' %>

<%= link_to 'Show', @scanner_hardware %> |
<%= link_to 'Back', scanner_hardwares_path %>

app/views/scanner_hardwares/index.html.erb
<h1>Listing scanner_hardwares</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Hardware group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scanner_hardwares.each do |scanner_hardware| %>
  <tr>
    <td><%= scanner_hardware.name %></td>
    <td><%= scanner_hardware.hardware_group %></td>
    <td><%= link_to 'Show', scanner_hardware %></td>
    <td><%= link_to 'Edit', edit_scanner_hardware_path(scanner_hardware) %></td>
    <td><%= link_to 'Destroy', scanner_hardware, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scanner hardware', new_scanner_hardware_path %>

app/views/scanner_hardwares/new.html.erb
<h1>New scanner_hardware</h1>

<%= render 'form' %>

<%= link_to 'Back', scanner_hardwares_path %>

app/views/scanner_hardwares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @scanner_hardware.name %>
</p>

<p>
  <b>Hardware group:</b>
  <%= @scanner_hardware.hardware_group %>
</p>


<%= link_to 'Edit', edit_scanner_hardware_path(@scanner_hardware) %> |
<%= link_to 'Back', scanner_hardwares_path %>