config/routes.rb
PandaShared::Application.routes.draw do
  resources :series_sets

  resources :series_log_items

  resources :series

  resources :series_scenarios

  resources :diagnosis_methods

  resources :diagnoses

  resources :scanner_hardwares

  resources :mri_scans

  resources :races

  resources :researchers

  resources :appointments

  resources :visits

  resources :enrollments

  resources :participants

  root :to => "participants#index"

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :participant
  has_many :enrollment_visit_memberships
  has_many :visits, :through => :enrollment_visit_memberships
  delegate :reggieid, :initials, :to => :participant, :prefix => true
  
  default_scope order :enumber
  
  acts_as_reportable :except => ['created_at', 'updated_at']
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  # GET /enrollments
  # GET /enrollments.xml
  def index
    @search = default_search(Enrollment)
    
    # @search = Enrollment.search(params[:search])
    @enrollments = @search.relation.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @enrollments }
    end
  end

  # GET /enrollments/1
  # GET /enrollments/1.xml
  def show
    @enrollment = Enrollment.find(params[:id])
    @visits = @enrollment.visits.order(:visit_number)
    logger.debug @visits.to_sql

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @enrollment }
    end
  end

  # GET /enrollments/new
  # GET /enrollments/new.xml
  def new
    @enrollment = Enrollment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @enrollment }
    end
  end

  # GET /enrollments/1/edit
  def edit
    @enrollment = Enrollment.find(params[:id])
  end

  # POST /enrollments
  # POST /enrollments.xml
  def create
    @enrollment = Enrollment.new(params[:enrollment])

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to(@enrollment, :notice => 'Enrollment was successfully created.') }
        format.xml  { render :xml => @enrollment, :status => :created, :location => @enrollment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @enrollment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /enrollments/1
  # PUT /enrollments/1.xml
  def update
    @enrollment = Enrollment.find(params[:id])

    respond_to do |format|
      if @enrollment.update_attributes(params[:enrollment])
        format.html { redirect_to(@enrollment, :notice => 'Enrollment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @enrollment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.xml
  def destroy
    @enrollment = Enrollment.find(params[:id])
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to(enrollments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollments_ul.html.erb
<p><b>Enrollments:</b></p>
<ul>
<% enrollments_ul.each do |e| %>
	<li><%= link_to e.enumber, e %></li>
<% end %>
</ul>

app/views/enrollments/_form.html.erb
<%= simple_form_for(@enrollment) do |f| %>
  <% if @enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @enrollment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.association :participant, :label_method => :reggie_initials %>
  <%= f.input :enroll_date %>
  <%= f.input :enumber %>
  <%= f.input :recruitment_source %>
	<%= f.input :withdrawl_reason %>

	<%= f.button :submit %>

  <!-- <div class="field">
    <%#= f.label :participant %><br />
    <%#= f.text_field :participant %>
  </div>
  <div class="field">
    <%#= f.label :enroll_date %><br />
    <%#= f.date_select :enroll_date %>
  </div>
  <div class="field">
    <%#= f.label :enumber %><br />
    <%#= f.text_field :enumber %>
  </div>
  <div class="field">
    <%#= f.label :recruitment_source %><br />
    <%#= f.text_field :recruitment_source %>
  </div>
  <div class="field">
    <%#= f.label :withdrawl_reason %><br />
    <%#= f.text_area :withdrawl_reason %>
  </div>
  <div class="actions">
    <%#= f.submit %>
  </div> -->
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render 'form' %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Destroy', @enrollment, :confirm => 'Are you sure?', :method => :delete %></td>

app/views/enrollments/index.html.erb
<h1>Listing enrollments</h1>

<table>
	<tfoot><tr><td colspan="8"><%= paginate @enrollments %></td></tr></tfoot>
  <tr>
    <th><%= sort_link @search, :enumber %></th>
    <th><%= sort_link @search, :participant_reggieid, "Participant" %></th>
		<th>Number of Visits</th>
    <th><%= sort_link @search, :enroll_date %></th>
    <th><%= sort_link @search, :recruitment_source %></th>
    <th><%= sort_link @search, :withdrawl_reason %></th>
  </tr>

<% @enrollments.each do |enrollment| %>
  <tr>
    <td><%= link_to enrollment.enumber, enrollment %></td>
    <td><%= link_to "#{enrollment.participant_reggieid} (#{enrollment.participant_initials})", enrollment.participant unless enrollment.participant.blank? %></td>
    <td><%= enrollment.visits.count %></td>
    <td><%= enrollment.enroll_date %></td>
    <td><%= enrollment.recruitment_source %></td>
    <td><%= enrollment.withdrawl_reason %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enrollment', new_enrollment_path %>

<%= form_for @search do |f| %>
	<p>
		<%= f.label :enumber_like %>
		<%= f.text_field :enumber_like %>
	</p>
	<p class="button"><%= f.submit "Search" %></p>
<% end %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render 'form' %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Participant:</b>
  <%= link_to @enrollment.participant_initials, @enrollment.participant unless @enrollment.participant.blank? %>
</p>

<p>
  <b>Enroll date:</b>
  <%= @enrollment.enroll_date %>
</p>

<p>
  <b>Enumber:</b>
  <%= @enrollment.enumber %>
</p>

<p>
  <b>Recruitment source:</b>
  <%= @enrollment.recruitment_source %>
</p>

<p>
  <b>Withdrawl reason:</b>
  <%= @enrollment.withdrawl_reason %>
</p>
<p>
	<b>Visits:</b>
	<ul>
	<% @visits.each do |v| %>
		<li><%= link_to "#{v.visit_number} - #{v.visit_date}", v %></li>
	<% end %>
	</ul>
</p>


<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>