config/routes.rb
PandaShared::Application.routes.draw do
  resources :series_sets

  resources :series_log_items

  resources :series

  resources :series_scenarios

  resources :diagnosis_methods

  resources :diagnoses

  resources :scanner_hardwares

  resources :mri_scans

  resources :races

  resources :researchers

  resources :appointments

  resources :visits

  resources :enrollments

  resources :participants

  root :to => "participants#index"

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  # GET /series
  # GET /series.xml
  def index
    @search = default_search(Series)
    @series = @search.relation.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @series }
    end
  end

  # GET /series/1
  # GET /series/1.xml
  def show
    @series = Series.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @series }
    end
  end

  # GET /series/new
  # GET /series/new.xml
  def new
    @series = Series.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @series }
    end
  end

  # GET /series/1/edit
  def edit
    @series = Series.find(params[:id])
  end

  # POST /series
  # POST /series.xml
  def create
    @series = Series.new(params[:series])

    respond_to do |format|
      if @series.save
        format.html { redirect_to(@series, :notice => 'Series was successfully created.') }
        format.xml  { render :xml => @series, :status => :created, :location => @series }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @series.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /series/1
  # PUT /series/1.xml
  def update
    @series = Series.find(params[:id])

    respond_to do |format|
      if @series.update_attributes(params[:series])
        format.html { redirect_to(@series, :notice => 'Series was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @series.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.xml
  def destroy
    @series = Series.find(params[:id])
    @series.destroy

    respond_to do |format|
      format.html { redirect_to(series_index_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= simple_form_for(@series) do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.association :series_set %>
  <%= f.input :position %>
  <%= f.input :pfile %>
  <%= f.button :submit %>
<% end %>

app/views/series/_series.html.erb
<tr>
	<th><%= link_to series.series_set.setname, series.series_set unless series.series_set.blank? %></th>
	<th><%= link_to series.position, series %> <!-- (<%#= series.id %>) --></th>
	<td><%= series.formatted_pfile %></td>
	<td><%= series.series_metainfo.series_description unless series.series_metainfo.blank? %> (<%= series.series_metainfo.id unless series.series_metainfo.blank? %>)</td>
	<td><%= link_to series.pulse_sequence.description, series.pulse_sequence unless series.pulse_sequence.blank? %> (<%= series.pulse_sequence.id unless series.pulse_sequence.blank? %>)</td>
	<td><%= link_to "#{series.scan_task.description} (#{series.scan_task.id})", series.scan_task unless series.scan_task.blank? %></td>
	<!-- <td><%#= link_to series.series_log_items.collect {|item| link_to "#{item.description if item.series_scenario.present?} (#{item.setname  if item.series_scenario.present?})", item}.join(", ").html_safe %></td> -->
	<td><%= display_agreement(series.series_detail_agreement) unless series.series_detail_agreement.blank? %></td>
</tr>

app/views/series/edit.html.erb
<h1>Editing series</h1>

<%= render 'form' %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

app/views/series/index.html.erb
<h1>Listing series</h1>

<table>
  <tr>
    <th>Order</th>
    <th>Appointment</th>
    <th>Pfile</th>
		<th>Scenario</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
	<tfoot><tr><td colspan="7"><%= paginate @series %></td></tr></tfoot>

<% @series.each do |series| %>
  <tr>
    <td><%= series.position %></td>
		<td><%= link_to series.appointment_date, series.appointment unless series.appointment.blank? %></td>
    <td><%= series.pfile %></td>
		<td><%= series.series_log_items.collect{|item| link_to item.description, item}.join(", ").html_safe %></td>
    <td><%= link_to 'Show', series %></td>
    <td><%= link_to 'Edit', edit_series_path(series) %></td>
    <td><%= link_to 'Destroy', series, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<h1>New series</h1>

<%= render 'form' %>

<%= link_to 'Back', series_index_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Appointment:</b>
  <%= link_to @series.appointment_date, @series.appointment %>
</p>

<p>
  <b>SeriesSet:</b>
  <%= link_to @series.setname, @series.series_set if @series.series_set %>
</p>


<p>
  <b>Order:</b>
  <%= @series.position %>
</p>

<p>
  <b>Pfile:</b>
  <%= @series.pfile %>
</p>


<% unless @series.series_log_items.blank? %>
<%= render @series.series_log_items %>
<% else %>
<h3>No Log Items</h3>
<% end %>

<% unless @series.series_metainfo.blank? %>
<%= render @series.series_metainfo  %>
<% else %>
<h3>No Series Metainfo</h3>
<% end %>

<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>